gsb_connexion:
    path:     /
    defaults: { _controller: GsbBundle:Connexion:connexion }

gsb_connexion2:
    path:     /connexion
    defaults: { _controller: GsbBundle:Connexion:connexion }

gsb_deconnexion:
    path:     /deconnexion
    defaults: { _controller: GsbBundle:Connexion:deconnexion }
    
gsb_consulterHistorique:
    path:   /consulterHistorique
    defaults: { _controller: GsbBundle:Consulter:consulterHistorique }
    
gsb_consulterARembourser:
    path:   /consulterARembourser
    defaults: { _controller: GsbBundle:Consulter:consulterARembourser }

gsb_consulterAValider:
    path:   /consulterAValider
    defaults: { _controller: GsbBundle:Consulter:consulterAValider }

gsb_detailFiche:
    path:   /detailFiche/{id}
    defaults: { _controller: GsbBundle:Detail:detailFiche }
    
gsb_detailFicheARembourser:
    path:   /detailFicheARembourser/{id}
    defaults: { _controller: GsbBundle:Detail:detailFiche  }
    
gsb_detailFicheAValider:
    path:   /detailFicheAValider/{id}
    defaults: { _controller: GsbBundle:Detail:detailFicheAValider }
