gsb_connexion:
    path:     /
    defaults: { _controller: GsbBundle:Connexion:connexion }

gsb_connexion2:
    path:     /connexion
    defaults: { _controller: GsbBundle:Connexion:connexion }

gsb_deconnexion:
    path:     /deconnexion
    defaults: { _controller: GsbBundle:Connexion:deconnexion }
    
gsb_consulter:
    path:   /consulter
    defaults: { _controller: GsbBundle:Consulter:consulter }
    
gsb_consulterA:
    path:   /consulterA
    defaults: { _controller: GsbBundle:Consulter:consulterA }
    
gsb_consulterB:
    path:   /consulterB
    defaults: { _controller: GsbBundle:Consulter:consulterB }